version: "3"

services:
  app:
    container_name: node-test-app
    build: .
    command: npm start
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app
    links:
      - mongodb
    environment:
      - PORT=3000
      - MONGO_CONNECTION=mongodb://mongodb:27017/node-test-app
  mongodb:
    container_name: mongoserver
    image: mongo
    ports:
      - "27017:27017"
