version: "3"

services:
  app:
    container_name: docker-app
    build: .
    command: npm start
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app
    links:
      - mongodb
  mongodb:
    container_name: mongoserver
    image: mongo
    ports:
      - "27017:27017"
  # mongo-seed:
  #   build: ./data
  #   ports:
  #     - "80:80"
  #   links:
  #     - mongodb
